### ISSUE TITLE
zircote/swagger-php 的版本能否兼容下， 现在是3.1.0

### ISSUE THREAD

**Issue by niezuxue** [ice-leng/hyperf-swagger#1]

**Comment by ice-leng** [comment]
建议使用 https://github.com/daodao97/apidog  叨叨 的 apidog
我在他扩展也做了一些贡献。支持模版输出

**Comment by ice-leng** [comment]
我这个 扩展 设计的  不太合理， 没有 结合 框架的验证器， 
没有通过注解自动生成swagger。json 代码，还要自己去写一遍生成文档

**Comment by niezuxue** [comment]
> 建议使用 https://github.com/daodao97/apidog 叨叨 的 apidog

我是因为之前用laravel 用的darkaonline/l5-swagger这个仓库中引入的 zircote/swagger-php，hyperf官方的swagger库也是引用的 zircote/swagger-php，所以我想着说在不改变这个仓库的写法的基础上来加一个ui界面。
叨叨的apidog写法和 zircote/swagger-php 有出入。这不想着省事。。

**Comment by ice-leng** [comment]
不会哦， 你可以不用 叨叨的  ui ，   框架启动 自动生成 swagger.json  
你去把这个json 内容直接拿来用三 
或者， 用黑暗料理
composer.json , 去吧 zircote/swagger-php  本地版本定死

**Comment by ice-leng** [comment]
虽然说 openapi  已经出 3.1.0 版本
但是 好像 swaggerui 最大支持  3.0.4

**Comment by ice-leng** [comment]
apidog 和 我的    都是基于 openapi 2.0  写的

**Comment by ice-leng** [comment]
如果 你使用 easyswoole 
https://github.com/ice-leng/http-annotation-swagger 
我给 easyswoole 写了 swagger.   这个版本是 3.0.4

**Comment by niezuxue** [comment]
> 不会哦， 你可以不用 叨叨的 ui ， 框架启动 自动生成 swagger.json
> 你去把这个json 内容直接拿来用三
> 或者， 用黑暗料理
> composer.json , 去吧 zircote/swagger-php 本地版本定死

框架启动有自动生成swagger.json么？

**Comment by niezuxue** [comment]
我现在准备用swagger-api/swagger-ui

**Comment by ice-leng** [comment]
> 我现在准备用swagger-api/swagger-ui

这个就是 官方的 swagger  ui
